[project]
name = "statuspi"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kevin Woods", email = "34251111+woody05@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=26.2.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
statuspi = "statuspi:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
